#!/bin/bash

set -eu
set -x

if [ "$PAM_TYPE" = "close_session" ]; then
  if zfs mount | grep -P "\b$volname\b" ; then
    # try to unmount the volume after this finishes
    { sleep 15s; eval zfs unmount -u "~$PAM_USER" ; } &
  fi
fi
